    
main:
  - name: Articles
    url: /articles/
    weight: -115  
  - name: Books
    url: /books/
    weight: -109
  - name: Forum
    url: /forum/
    weight: -108
  - name: About
    identifier: about
    url: /about/
    weight: -100
  - name: Mission and Values
    parent: about
    weight: 10
    url: /about/mission-and-values/
  - name: Submission Guide
    parent: about
    weight: 9
    url: /about/authors-guide/
  - name: Editorial Policy
    weight: 8
    parent: about
    url: /about/editorial/
  - name: Contact Us
    weight: 7
    parent: about
    url: /about/contact/


