title: "Peaceful Science"
baseURL: "https://peacefulscience.org/"
languageCode: "en-us"

enableGitInfo: true
disableAliases: true

server:
  headers:
    - for: /font/*.woff2
      values:
        Access-Control-Allow-Origin: "*"

minify:
  disableXML: true
  minifyOutput: true

related:
  includeNewer: true
  indices:
  - name: categories
    weight: 100
  - name: authors
    weight: 50
  - name: section
    weight: 50
  threshold: 80
  toLower: false
  
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
        
cache:
  getjson:
    dir: :cacheDir/:project
    maxAge: 1m

mediaTypes:
  text/prs.netlify:
    suffixes: [""]
    delimiter: ""
    
outputformats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  redir:
    mediatype: text/prs.netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  precompute:
    basename: precomptute.txt
    notAlternative: true
    weight: 1
  HTML:
    weight: 2 
   
outputs:
  home: ["precompute", "HTML", "RSS", "redir"]

params:
  baseGitHub: "https://github.com/PeacefulScience/peacefulscience.org/"
  sitemap_min_date: "2021-09-10"
  algolia:
    vars: ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params: ["categories", "tags"]
  headerType: none
  imagecdn: 8l2ic7fx.cdn.imgeng.in
  logo: /img/design/logo-black-square.png

paginate: 12

googleAnalytics: G-BHPH29YM44

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
 
sitemap:
  priority: 0.5

permalinks: 
  article: /:sections/:title/

